#!/bin/sh

MDTMACPATH="tmac/"
reffile="/tmp/.mdroff-ref$$"
tocfile="/tmp/.mdroff-toc$$"
pgnfile="/tmp/.mdroff-pgn$$"
FIFO="/tmp/.mdroff-post$$"
TMP="/tmp/.mdroff-out$$"

#
# mdpost -- filters label definitions and numbered headings
#
mdpost()
{
    awk -v reffile="$reffile" -v pgnfile="$pgnfile" '
/^LA:[ \t]/ {
	_FS = FS
	FS = "\t"
	$0 = $0
	printf "%s\t%s\t%s\t%s\n", $2, $3, $4, $5 >> reffile
	FS = _FS
	next
}

/^NH:[ \t]/ {
	FS_prev = FS
	FS = "\t"
	$0 = $0
	printf "%s\t%s\n", $2, $3 >> pgnfile
	FS = FS_prev
	next
}

{
	print $0
}'
}

mdpre()
{
    awk -v reffile="$reffile" -v tocfile="$tocfile" -v pgnfile="$pgnfile" '
BEGIN {
	QUOTE = "\""
	SLASH = "\\"
	tocfile_sourced = 0

	H1 = 0; H2 = 0; H3 = 0; H4 = 0

	system("touch " reffile)

	_FS = FS
	FS = "\t"
	
	while ((getline < reffile) > 0) {
		if (NF < 4)
			continue
		name = $1
		mdref[name, "text"] = $2
		mdref[name, "page"] = $3
		mdref[name, "chapter"] = $4
	}

	close(reffile)
	system("rm -f " reffile)

	while ((getline < pgnfile) > 0) {
		if (NF < 2)
			continue
		h = $1; page = $2
		tocpg[h] = page
	}

	close(pgnfile);
	system("rm -f " pgnfile)

	FS = _FS
}

/^\.TC[ \t]*/ {
	if (tocfile_sourced) {
		print ".TC"
	} else {
		system("touch " tocfile)
		print ".so " tocfile
		tocfile_sourced = 1
		print ".TC"
		printf ".lf %d\n", NR
	}
	next
}

/^\.LA / {
	#   issue troff directive to print label definition,
	# page, and chapter
	#   prevent duplicated interpolation of 3-d argument
	# via temporary variable
	printf ".ds L@ \"%s\n", $3
	printf ".LA \\*(L@\n"
	printf ".tm LA:\t%s\t\\*(L@\t\\n%\t\\n[H1]\n", $2
	printf ".lf %d\n", NR
	next
}

/^\.LQ / {
	# get label and define label text, page, and chapter.
	name = $2
	print $0
	print ".ds LN " name
	if ((name, "text") in mdref) {
		print ".ds LT \"" mdref[name, "text"]
		print ".nr LP " mdref[name, "page"]
		print ".nr LC " mdref[name, "chapter"]
	} else {
		#print ".tm \\n(.F:" NR ": Warning! Label `" name "'\'' is not defined!"
	}
	printf ".lf %d\n", NR
	next
}

/^\.H[1-4] / {

	print $0

	level = substr($1, 3)+0

	if (level == 1) {
		H1++
		H2 = 0
		HS = H1
	} else if (level == 2) {
		H2++
		HS = H1 "." H2
	}
	HS = HS "."

	if (level <= 2)
		printf ".tm NH:\t\\*[HS]\t\\n[%]\n"

	$1 = ""
	FS_prev = FS
	FS = ""
	$0 = $0
	line = ""
	quote = 0
	sep = 0
	
	for (i = 1; i <= NF; i++) {
		if (quote) {
			for ( ; i <= NF; i++) {
				if ($i == SLASH && $(i+1) == QUOTE) {
					line = line QUOTE
					i += 1
					continue
				}
				if ($i == QUOTE) {
					quote = 0
					line = line " "
					break
				}
				line = line $i
			}
		} else {
			while ($i == " ")
				i++
			for ( ; i <= NF; i++) {
				if ($i == SLASH && $(i+1) == QUOTE) {
					line = line QUOTE
					i += 1
					continue
				}
				if ($i == " ") {
					line = line " "
					sep = 1
					break
				}
				if ($i == QUOTE) {
					quote = 1
					if (!sep)
						line = line " "
					sep = 0
					break
				}
				line = line $i
			}
		}
	}

	FS = FS_prev

	if (quote)
		print "mdroff: Warning! unterminated quote at line " NR > "/dev/stderr"

	if (level == 1) {
		if ((pgno = tocpg[HS]) == "")
			pgno = "???"
		print ".XS\n" \
		      ".sp 0.3v\n" \
		      ".XA " pgno "\n" \
		      "\\s+4\\\n" \
		      ".XM \\s+4" HS "\\s0\n" \
		      "\\&" line "\n" \
		      "\\s0\n" \
		      ".XE\n" \
		      ".XS\n" \
		      ".sp 0.3v\n" \
		      ".XE" >> tocfile
	} else if (level == 2) {
		if ((pgno = tocpg[HS]) == "")
			pgno = "???"
		print ".XS\n" \
		      ".XA " pgno " 12n\n" \
		      ".XM " HS "\n" \
		      "\\&" line "\n" \
		      ".XE" >> tocfile
	}

	printf ".lf %d\n", NR

	next
}

{
	print
}
'
}

cleanup()
{
	rm -f "$FIFO" "$TMP"
	rm -f "$reffile" "$tocfile" "$pgnfile"
}

usage()
{
	cat <<-EOF
	Usage: mdroff [OPTIONS] FILE ...

	  -h		print help message
	  -d name=s	define string \`name' as \`s'
	  -e		preprocess with eqn
	  -g		preprocess with grn
	  -G		preprocess with grap
	  -p		preprocess with pic
	  -r name=n	define register \`n' as \`n'
	  -R		preprocess with refer
	  -s		preprocess with soelim
	  -t		preprocess with tbl
	  -Tdev		set output device (\`ps' for PostScript or \`pdf' for PDF)
	
	Example:
	  $ mdroff -Tpdf -e -t example.tr >example.pdf

	EOF
}

gropost="grops"
cmdpipe="mdpre | GROFF_TMAC_PATH=\"$MDTMACPATH\" groff \${GROFFOPTS}"
GROFFOPTS="-Z -Tps -dpaper=$(cat /etc/papersize) -md"

while getopts :d:eghpr:stGRT: f
do
	case "$f" in
	d) GROFFOPTS="$GROFFOPTS -d $OPTARG";;
	e) GROFFOPTS="$GROFFOPTS -e";;
	g) GROFFOPTS="$GROFFOPTS -g";;
	h) usage; exit 0;;
	p) GROFFOPTS="$GROFFOPTS -p";;
	r) GROFFOPTS="$GROFFOPTS -r $OPTARG";;
	s) GROFFOPTS="$GROFFOPTS -s";;
	t) GROFFOPTS="$GROFFOPTS -t";;
	G) GROFFOPTS="$GROFFOPTS -G";;
	R) GROFFOPTS="$GROFFOPTS -R";;
	T) case $OPTARG in
		ps)  ;;
		pdf) gropost="grops | ps2pdf -dUseCIEColor=true -dPDFSETTINGS=/printer -";;
		*)   usage; exit 1;;
	   esac;;
	*) usage; exit 1;;
	esac
done

shift $((OPTIND-1))

test $# -lt 1 && { usage; exit 1; }

trap 'cleanup; exit 2;' INT QUIT
trap 'cleanup' 0

mkfifo -m660 "$FIFO" || { echo "failed to create FIFO" >&2; exit 1; }

if [ "$LC_ALL" = "ru_RU.UTF-8" -o "$LANG" = "ru_RU.UTF-8" ]; then
	GROFFOPTS="${GROFFOPTS} -mru"
	cmdpipe="iconv -futf8 -tkoi8r -- \"$@\" | preconv -eKOI8R | $cmdpipe"
else
	cmdpipe="cat \"$@\" | $cmdpipe"
fi

npass="0"
csum=""; csum2="-"

while [ "$csum" != "$csum2" ]; do
	csum2="$csum"
	rm -f "$tocfile"
	mdpost <"$FIFO" >&2 &
	eval "${cmdpipe} 2>${FIFO} 1>${TMP}"
	csum=$(md5sum "$TMP" | cut -d' ' -f1)
	npass=$((npass+1))
done

eval "$gropost" <"$TMP"

#printf "Done in %d pass%s\n" $npass $(test $npass -gt 1 && echo "es") >&2

exit 0
